- newbasic/Makefile.am
- newbasic/oncsBuffer.h
- newbasic/oncsCollection.h
- newbasic/oncsEvent.cc
- newbasic/oncsSubConstants.h
- newbasic/oncsSub_idtpcfeev1.cc
- newbasic/oncsSub_idtpcfeev1.h
- newbasic/oncs_mnemonic.cc
I added the "TPCFEE" (hitformat 97) decoder for the sampa prototype board.
> mlp - added the "TPCFEE" (hitformat 97) 

- newbasic/Makefile.am
- newbasic/oncsCollection.h
- newbasic/oncsEvent.cc
- newbasic/oncsSubConstants.h
- newbasic/oncsSub_iddreamv0.cc
- newbasic/oncsSub_iddreamv0.h
- newbasic/oncsSubevent.cc
- newbasic/oncs_mnemonic.cc
- newbasic/packetConstants.h
I merged the changes that had accumulated, especially the addition of the dream chip decoder, with Chris' concurrent changes related to the root6 adoption.
> merge slightly diverged root6-related changes with other changes

- newbasic/Makefile.am
fallout from having to include packet_hbd_fpgashort.h
> install all includes needed for including packet_hbd_fpgashort.h

- newbasic/A_Event.cc
- newbasic/Makefile.am
- newbasic/configure.ac
- newbasic/packetConstants.h
- newbasic/packet_collection.h
- newbasic/packet_fvtx_dcm0.cc
- newbasic/packet_fvtx_dcm0.h
- newbasic/packet_mnemonic.cc
- pmonitor/configure.ac
- pmonitor/pmonitor.cc
replaced "gawk" with "awk" in configure scripts
updated pmonitor phelp() text
the main thing here is that we brought the FVTX decoder 425  back into the sPHENIX fold so the
test beam data can be analyzed in the sPHENIX setting.
> cumulative updates

- newbasic/oncsSub_idtpcfeev2.cc
- newbasic/oncsSub_idtpcfeev2.h
made a lot of changes to the tcp_feev2 decoder to deal with data corruption problems as they appear in new data files.
> mlp - lots of changes to the tcp_feev2 decoder

- newbasic/configure.ac
This PR fixes the final warning in our build
> fix warning about use of AM_INIT_AUTOMAKE

- newbasic/Makefile.am
previously I didn't install the root pcm files right.
> mlp - added the proper install for the root pcm files

- newbasic/Makefile.am
- newbasic/simpleRandom.cc
- newbasic/simpleRandom.h
It is iternal to the class only, so I renamed it "xbyte". Oh well.
> Fixed an issue with a typedef names "byte" in simpleRandom.

- newbasic/oncsSub_iddigitizerv1.cc
- newbasic/oncsSub_iddigitizerv1.h
- newbasic/oncsSub_idmvtxv0.cc
- newbasic/oncsSub_idmvtxv0.h
- newbasic/oncsSub_idmvtxv1.cc
- newbasic/oncsSub_idmvtxv1.h
- newbasic/oncsSub_idtpcfeev2.cc
- newbasic/oncsSub_idtpcfeev2.h
worked around a hidden overloaded function warning with some of the classes.
> mlp - worked around a hidden overloaded function warning

- newbasic/oncsSub_idfnalmwpc.cc
De-fanged a memset of a structure that contains STL containers. 
Got flagged by Mr. Jenkins, and he is right.
> mlp - de-fanged a memset of a structure that contains STL containers.

- newbasic/Cframe.C
- newbasic/caen_correction.cc
- pmonitor/Makefile.am
- pmonitor/configure.ac
A "cumulative" update of 3 commits that came up in the currently ongoing test beam.
> removed unused variables, pcm files install, fix in header include

- newbasic/caen_correction.cc
Some of the commits were breaking style so later it will get in the way of sed-type updates.
> there were numerous upstream commits that I'm still catching up on.

- newbasic/caen_correction.cc
- newbasic/caen_correction.h
- newbasic/oncsSub_idcaenv1742.cc
The updates are largely from Alexander, who worked on the Fermilab data a lot
> Enhancing the CAEN 1742 support

- pmonitor/writePmonProject.pl
To make it easier, I added a shell script (and a root macro) to be generated for a new project.
> modified writePmonproject  to add a shell script for starting a given pmonitor project

- newbasic/fileEventiterator.cc
- newbasic/oncsEventiterator.cc
Buffer sizes in PRDFs are always multiples of 8KBytes. I was reading as many records as needed to get the entire buffer. Some file systems work better with larger read chunks. I now calculate the entire  buffer size and read it in one go, so the OS can pick the proper physical size that works best.
> mlp - per Chris' suggestion, make one big buffer read in one fell swoop

- newbasic/configure.ac
adding another warning suppression
> add gcc 12 warning suppression

- newbasic/oncsSub_idtpcfeev3.cc
Following https://sphenix-intra.sdcc.bnl.gov/WWW/elog/TPC/75 , just quick fix so decoder allows for data stream containing more than just the FEE waveform data in the PCIe multiplexer stream.
> Update the demux to allow stream contain more than FEE wf data

- newbasic/oncsSub_idinttv0.cc
clang stumbled over an unused local variable - commented out
> comment out unused hit_itr to make clang happy

- newbasic/A_Event.cc
- newbasic/Makefile.am
- newbasic/packetConstants.h
- newbasic/packet_collection.h
- newbasic/packet_idll1v1.cc
- newbasic/packet_idll1v1.h
- newbasic/packet_mnemonic.cc
This commit adds the LL1 decoder as packet type number 141 IDLL1_20S
> djl -- adding LL1 decoder

- newbasic/Makefile.am
- newbasic/oncsCollection.h
- newbasic/oncsEvent.cc
- newbasic/oncsSubConstants.h
- newbasic/oncsSub_idgl1v0.cc
- newbasic/oncsSub_idgl1v0.h
- newbasic/oncsSub_idmvtxv3.cc
- newbasic/oncs_mnemonic.cc
This adds a decoder for the GL1 data, and other incremental improvements.
> cumulative update 

- newbasic/oncsSub_idtpcfeev3.cc
Fix scan build found potential memory leak 
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/Build-ScanBuild-gcc12/865/clang-analyzer/new/source.77c15c48-f975-461a-bcd4-07f11ae3db31/#64
> fix potential memory leak at invalid magic word match

- newbasic/oncsSub_idinttv0.cc
- newbasic/oncsSub_idinttv0.h
- newbasic/oncsSub_idmvtxv3.cc
- newbasic/oncsSub_idmvtxv3.h
This PR contains the snapshot-commit of the MVTX decoder that is in a state that it works as well as I could make it.
It also has the updated INTT decoder that knows about a new field in the raw data.
> cumulative update

- newbasic/A_Event.cc
- newbasic/packetConstants.h
- newbasic/packet_idll1v1.cc
- newbasic/packet_idll1v1.h
- newbasic/packet_mnemonic.cc
Edited the LL1 decoder for new data format with 7 bits allocated to the NHITS data
> djl -- edited LL1 decoder

- newbasic/mvtx_decoder/GBTLink.h
- newbasic/oncsSub_idmvtxv3.cc
- newbasic/oncsSub_idmvtxv3.h
- newbasic/packet.h
This PR implements some fixes in the MVTX decoder
> Fixes to MVTX decoder when decoding more than a packet value

- newbasic/lzobuffer.cc
I added support for lzo-compressed sPHENIX-format raw data. 
I still need to retrofit dpipe with the ability to write them, but that will be more complex. I'm about to commit a RCDAQ version that can generate them.
> mlp - added support for lzo-compressed sPHENIX-format raw data.

- newbasic/packet_iddigitizerv3.cc
Even and Odd channels are swapped between ADC and detector definitions, implemented it into the decoder
> djl -- changed the evens to odds on digitizer decoder

- newbasic/Makefile.am
- newbasic/mvtx_decoder/DecodingStat.cxx
- newbasic/mvtx_decoder/DecodingStat.h
- newbasic/mvtx_decoder/GBTLink.h
A few of YCM's commits got into a strange state in git. I didn't want to risk doing strange things to the repo. I pulled the individual files and re-committed them fresh.
> mlp - re-committing YCM's changes.

- newbasic/Makefile.am
- newbasic/eventClient.cc
- newbasic/eventLinkDef.h
- newbasic/eventReceiverClient.cc
- newbasic/eventReceiverClient.h
- newbasic/eventServer.cc
- pmonitor/pmonitor.h
I added a new "event" service that is meant to server events from the sPHENIX GL1 system but is actually a but more generic. It keeps an adjustable-depth list of events in a container and dishes them out to clients. In this way it is possible to get the GL1 information to the monitoring processes. 
This currently works for the triggered data where the event number matches. Working on the SRO data API next.
> new eventServer and eventReceiverClient interface

- newbasic/A_Event.cc
> djl -- 16 sample added

- newbasic/oncsSub_idgl1v0.cc
- newbasic/oncsSub_idgl1v0.h
Those only give new meaning to existing fields, so there is no new
hitformat needed.
> mods for the recent changes in the GL1 data format

- newbasic/packet_iddigitizerv2.cc
- newbasic/packet_iddigitizerv2.h
add clock/event rollover counter for iddigitizer v2 for MBD
> jbp -- add clock/event rollover counter for iddigitizer v2

- newbasic/packet_idll1v2.cc
fix to number of trigger words in a packet.
> Ll1 decoder

- newbasic/packet_iddigitizerv3.cc
- newbasic/packet_iddigitizerv3.h
upgraded the packet_iddigitizerv3 to an lValue to avoid signed int iValue to go negative.
> packet_iddigitizerv3 "CLOCK" API now an lValue

- newbasic/oncsSub_idtpcfeev3.cc
My bad I should have added this boundary protection. Sorry for that.
> fixed the problem to avoid corrupted data going beyond time boundary of 1024

- newbasic/oncsSub_idtpcfeev3.cc
I included a check of packet length defined by SAMPA and that from FEE header, and rejected those not consistent each other. CRC check is not done after this. People would be happy to see less CRC errors by this.
> suppressed errors and drop those rejected by the packet length check

- newbasic/mvtx_decoder/GBTLink.h
- newbasic/oncsSub_idmvtxv3.cc
This PR fixes some false errors during the HBF integrity check in case of OM.
> ycm - update hbf integrity check

- newbasic/eventReceiverClient.cc
- newbasic/oncsSub_idgl1v0.cc
- newbasic/oncsSub_idgl1v0.h
- newbasic/packet_iddigitizerv3.cc
some safety belts added to prevent issues we have seen in the online monitoring.
> Safet belts in decoders and the eventReceiverClient

- newbasic/packet_idll1v2.cc
- newbasic/packet_idll1v2.h
Chris, I made =it so number of channels, by iValue(0, "CHANNELS") returns the total number of readout words.. accurately.
> djl -- added nchannels to be accessible

- newbasic/oncsSub_idtpcfeev4.cc
- newbasic/oncsSub_idtpcfeev4.h
So-called GTM modebit events should have been also implemented. This is now implemented.
> Added so-called GTM Modebit events in the TPC decoder

- newbasic/oncsSub_idinttv0.cc
- newbasic/oncsSub_idinttv0.h
added a new API for the INTT that will give us the list of BCO irregardless of it being attached to a hit.
> mlp - added a new API for the INTT that will give us the list of BCOs

- newbasic/eventServer.cc
I added features to the eventServer to allow for better testing of the online monitoring code.
> Event server updates

- newbasic/eventClient.cc
- newbasic/packet_iddigitizerv3.cc
- fix in eventClient that ignored a host parameter
- fix in packet_iddigitizerv3 that created an infinite loop
> eventClient and digitizer fix

- newbasic/eventServer.cc
I implemented a new management scheme for the events in eventServer
> mlp - a new management scheme for the events in eventServer

- newbasic/mvtx_decoder/GBTLink.h
- newbasic/mvtx_decoder/mvtx_utils.h
- newbasic/oncsSub_idmvtxv3.cc
This PR aims to fix the OM crash problem which happened very often in the last week [Mattermost LINK](https://chat.sdcc.bnl.gov/sphenix/pl/pyemyxsggjyr8y7dehtn1xbsic). We add the checkRDH function after decoding RDH refer to [coresoftware decoder](https://github.com/sPHENIX-Collaboration/coresoftware/pull/2989).
> Mvtxdecoder

- newbasic/A_Event.cc
- newbasic/A_Event.h
- newbasic/Event.h
- newbasic/buffer.h
- newbasic/fileEventiterator.cc
- newbasic/gzbuffer.cc
- newbasic/gzbuffer.h
- newbasic/lzobuffer.cc
- newbasic/lzobuffer.h
- newbasic/mvtx_decoder/GBTLink.h
- newbasic/mvtx_decoder/mvtx_utils.h
- newbasic/oncsBuffer.cc
- newbasic/oncsBuffer.h
- newbasic/oncsEvent.cc
- newbasic/oncsEvent.h
- newbasic/oncsSub_idgl1v1.cc
- newbasic/oncsSub_idgl1v1.h
- newbasic/oncsSub_idmvtxv3.cc
- newbasic/oncsSubevent.h
- newbasic/packet.h
- newbasic/packet_A.h
- newbasic/packet_iddigitizerv3.cc
- newbasic/packet_iddigitizerv3.h
- newbasic/prdfBuffer.cc
- newbasic/prdfBuffer.h
A few long-overdue changes to the Event and packet interfaces. 
The getEvtSequence() and so on are now declared const. (Those APIs go back many years)
there is a new API std::vector<Packet *> getPacketVector() that augments the 1995-style getPacketList call (STL wasn't real thing then).
> Interface change

- newbasic/mvtx_decoder/GBTLink.cxx
- newbasic/mvtx_decoder/GBTLink.h
- newbasic/oncsSub_idmvtxv3.cc
Add the number of RDH Errors (fail checkRDH) in GBTLink.
> mvtx add RDH error counts

- newbasic/BufferConstants.h
- newbasic/Makefile.am
- newbasic/buffer.cc
- newbasic/bz2buffer.cc
- newbasic/bz2buffer.h
- newbasic/fileEventiterator.cc
- newbasic/lzobuffer.cc
- newbasic/lzobuffer.h
- newbasic/prdfcheck.cc
- newbasic/prdfsplit.cc
I mis-typed "bz2" in the branch name....
this adds support for the bz2-compressed  files.
> Bz2compression

- newbasic/mvtx_decoder/DecodingStat.h
- newbasic/oncsSub_idfnalmwpc.cc
- newbasic/oncsSub_idfnalmwpcv2.cc
Small changes (missing include, uninitialized variables) to compile with gcc14, c++20
> compile with gcc 14, c++20

- newbasic/oncsEvent.cc
- newbasic/oncsSubConstants.h
- newbasic/oncs_mnemonic.cc
New firmware with the clock sync will be introduced. The hit format will be updated following this, though the data format and thus the decoder don't change.
> New hit format for clock synced packet for TPC

- newbasic/mvtx_decoder/DecodingStat.cxx
- newbasic/mvtx_decoder/DecodingStat.h
- newbasic/mvtx_decoder/GBTLink.cxx
- newbasic/mvtx_decoder/GBTLink.h
- newbasic/mvtx_decoder/GBTWord.cxx
- newbasic/mvtx_decoder/GBTWord.h
- newbasic/mvtx_decoder/InteractionRecord.cxx
- newbasic/mvtx_decoder/InteractionRecord.h
- newbasic/mvtx_decoder/PayLoadCont.cxx
- newbasic/mvtx_decoder/PayLoadCont.h
- newbasic/mvtx_decoder/PayLoadSG.h
- newbasic/mvtx_decoder/PixelData.cxx
- newbasic/mvtx_decoder/PixelData.h
- newbasic/mvtx_decoder/mvtx_utils.h
- newbasic/oncsSub_idmvtxv3.cc
attempt to fix the increase memory issue.
> ycm - formatting and shrink memory

- newbasic/packet_iddigitizerv2.cc
- newbasic/packet_iddigitizerv3.cc
This PR prints the clock values in hex
> print clock values in hex for packet_iddigitizerv2/packet_iddigitizerv3
