sPHENIX-Collaboration/online_distribution

newbasic/packet_iddigitizerv2.cc, newbasic/packet_iddigitizerv2.h
The comment says it - we are dumping the per-board (and make the accessible via API call) values.
```
Packet  21351  5981  0 (Unformatted)    93 (IDDIGITIZERV2)
Evt Nr:      0
Clock:       22672
Nr Modules:  3
Channels:    192
Samples:     31
Det. ID:     0x5555
Mod. Addr:   0x3333
FEM Slot:          16      15      14
FEM Evt nr:         1       1       1
FEM Clock:      22542   22546   22534
Even chksum: 0xff14   calculated:  0xff14 ok
Odd chksum:  0x5bfb   calculated:  0x5bfb ok
```
=> mlp - APIs and a modified dump() function to bring out the per-board clocks, slots, event nrs.

newbasic/A_Event.cc, newbasic/packetConstants.h, newbasic/packet_iddigitizerv2.cc, newbasic/packet_mnemonic.cc
I added the digitizer hitformats to indicate that the packet contains 12 and 16 samples. 
This  is the poor man's version of going about it, but it's the best I can do. It is still possible to configure the readout one way and state the wrong number of samples in the hitformat, rather than to embed the information (and also allow an arbitrary number of samples, not just 12,16,31) in 5 spare bits in the payload somewhere, but this is not my code.
Now we have 
IDDIGITIZER_31S     93
IDDIGITIZER_12S     94
IDDIGITIZER_16S     95
=> mlp - add the digitizer hitformats for 12 and 16 samples.

newbasic/oncsSubevent.cc
fixed a rarely encountered issue that the padding value was ignored for a packet that doesn't have a dedicated decoder yet. This kicks in only during the development phase of a new packet. This was found during the development of the new MVTX packet.
=> mlp - fixed a rarely encountered issue that the padding value was ignored.

newbasic/packet_iddigitizerv2.cc
I brought out 16, rather than 14 bits from the value, and caused
the values to oscillate with higher bits set.
=> mlp -- a rather serious bug in the digitizer decoder.

newbasic/oncsSubConstants.h, newbasic/packetConstants.h
I also added an early version of the sPHENIX TPC data format, in addition to the (not yet implemented, btw) MM3 chip and the real-time clock data format.
=> mlp - added hitformats for the MM3 chip and real-time clock

newbasic/Makefile.am, newbasic/configure.ac, newbasic/eventLinkDef.h, newbasic/msgLinkDef.h, pmonitor/Makefile.am, pmonitor/configure.ac
Non I/O dictionaries are only needed for ROOT5, actually ROOT6 behaves badly when those dictionaries are added, ROOT6 gets the class info from their include files - basically all classes are available on the cmd line by default
=> build dictionaries only for root5

newbasic/Makefile.am
that one needs to be installed - it crashes downstream packages which include oEvent.h
=> install also EvtStructures.h

newbasic/oncsSub_iddreamv0.cc, newbasic/oncsSub_iddreamv0.h
turns out that is has yet another format variant, that
is now supported (multiple FEU reports in one jumbo network packet).
=> mlp - yet another modification of the DREAM chip decoder.

pmonitor/pmonitor.cc, pmonitor/pmonitor.h
I added the ability to selectively stop update threads that
have been started with pupdate(canvas_name). One can stop
all of them by pend_update() as before, or issue
pend_update(canvas_name) to stop only that thread.
=> Added the ability to selectively stop canvas update threads 

newbasic/oncsSubevent.h, newbasic/packet.h, newbasic/packet_A.h, newbasic/packet_hbd_fpga.h, newbasic/packet_hbd_fpgashort.h
Derived-classes can use this to set internal parameters. This was added to 
overcome the issues with packet_fpga and packet_fpga_short that 
need to be told what their number of samples is.
We can now replace the dreaded constructs such as
_packet = dynamic_cast<Packet_hbd_fpgashort *>
( _event->getPacket(PROTOTYPE3_FEM::PACKET_ID));
_packet->setNumSamples(PROTOTYPE3_FEM::NSAMPLES);
with
_event->getPacket(PROTOTYPE3_FEM::PACKET_ID)->setInternalParameter(PROTOTYPE3_FEM::NSAMPLES);
without the need for an unsafe cast.
The 2 HBD classes are currently the only ones that override that call. Let's keep
it that way.
This is not meant to be a free-for-all to add the need for such a thing.
The philosophy was and is that the packet payload must have all the
required information so it can be decoded …
=> mlp - added a "setInternalParameter" method to the top virtual Packet class.

newbasic/simpleRandom.cc
This PR removes the last register keyword. It is obsolete and clang 9 does not want to compile this anymore with -std=c++17
=> register keyword outlawed for c++17

pmonitor/configure.ac
had added c++11... back where we were before.
=> mlp -- removing the apparently offending compiler flag again.

newbasic/Makefile.am, newbasic/oncsSubevent.h
This PR adds installation of oncsSubevent.h which is pulled in by the ospBuffer.h. If using the installed includes #include <oncsSubConstants.h> does not work. It needs #include "oncsSubConstants.h" to locate it.
=> install oncsSubevent.h, replace <> by quotes for local include

newbasic/ospEvent.cc
This PR is a small patch (commenting out unused variable declaration) so jenkins lets our PRs pass
=> comment out unused variable so jenkins is happy

newbasic/Cframe.C, newbasic/Cpacket.C, newbasic/caen_correction.cc, newbasic/caen_correction.h, newbasic/configure.ac, newbasic/ddump.cc, newbasic/dpipe.cc, newbasic/oncsSub_idsrs_v01.cc, pmonitor/configure.ac, pmonitor/pmonstate.h
This PR fixes the clang warnings (unused variables commented out). I added -Werror to the compiler flags and suppressed some warnings I did not feel comfortable to fix in the configure.ac
=> Fix clang warnings

newbasic/configure.ac
version" approach also in newbasic. The recent version format that
root_config gives out broke that test.
=> mlp - fixed the root version test.

pmonitor/Makefile.am
This PR removes the pcm file from the Makefile.am. These files are only needed by ROOT6 for persistent classes which is not the case here.
=> no root 6 dictionary needed (also no pcm file)

pmonitor/Makefile.am, pmonitor/pmonstate.h
We had some back and forth about the proper installation of the pmonitor pcm files, which I initially botched. With Chris' help I _believe_ I got it right.
There was also a stray declaration line in a header file, looked like an inadvertent paste,  that I removed now; it generated warnings.
=> a new attempt to getthe pcm file installation right

newbasic/configure.ac, pmonitor/configure.ac
This PR adds compiler flags which suppress warnings caused by using -Wextra. For newbasic it is:
-Wno-unused-parameter -Wno-type-limits -Wno-unused-but-set-parameter
for pmonitor it is
-Wno-unused-parameter
=> suppress compiler warnings when using -Wextra

newbasic/oncsSub_idmvtxv2.cc
with the more stringent warnings I picked up a comparison between signed and unsigned int in the just merged mvtx code.
=> mlp - comparison between signed and unsigned int fixed

newbasic/packetConstants.h, newbasic/packet_w124.cc
This was a more than 20 years-old bug...
getDataLength()  returns the length of the payload in native units, so for example 20 shorts get reported as length 20. The gdump function in w2 and w1 assumed it's reported in units of int, and multiplied by 2 or 4, respectively.
=> mlp - issue with 16bit and 8bit packet data sizes in gdump

newbasic/oncsSubConstants.h, newbasic/packetConstants.h, newbasic/packet_w124.cc, pmonitor/Makefile.am, pmonitor/configure.ac
switched to the root-config method to get at compiler flags.
fixed an ifdef guard in a header file that clashed with another package.
=> ifdef guard fix

pmonitor/Makefile.am
This PR fixes running rootcint
[pinkenbu@rcas2601 pmonitor]$ rootcint  -f pmonitor_Dict.C  -noIncludePaths  -inlineInputHeader  -c -I. -I/phenix/u/pinkenbu/workarea/sPHENIX/gitrepov5/online_distribution/pmonitor -I/phenix/u/pinkenbu/workarea/sPHENIX/gitrepov5/install/include  -pthread -std=c++17 -m64 -I/cvmfs/sphenix.sdcc.bnl.gov/gcc-8.3/opt/sphenix/core/root-6.24.06/include /phenix/u/pinkenbu/workarea/sPHENIX/gitrepov5/online_distribution/pmonitor/pmonitor.h /phenix/u/pinkenbu/workarea/sPHENIX/gitrepov5/online_distribution/pmonitor/pmonstate.h /phenix/u/pinkenbu/workarea/sPHENIX/gitrepov5/online_distribution/pmonitor/pmonitorLinkDef.h
rootcint: for the   -s option: may not occur within a group!
rootcint: for the   -m option: may not occur within a group!
translated means rootcint …
=> rootcint does not like cflags

newbasic/oncsEvent.cc, newbasic/oncsSubConstants.h, newbasic/oncs_mnemonic.cc
This implements (or better, re-activates) the format when we read out directly through the controller, not the DCM2. We kept on building the decoder but had taken it out of the active hitformat dispatch.
=> standalone digitizer readout via the controller

newbasic/msg_buffer.cc, newbasic/msg_buffer.h
the ftime() call was marked obsolete a while ago. It starts disappearing in newer OS versions. I replaced it with the clock_gettime(...) system call that is part of the POSIX standard now.
=> mlp - replace the obsolete ftime(...) API with clock_gettime().

newbasic/oncsSubevent.cc, newbasic/oncsSubevent.h, newbasic/packet.h, newbasic/packet_A.cc, newbasic/packet_A.h
I added an API to change the packet id for a packet in memory.
This is useful to combine events from tests into full events.
=> mlp - added an API to change the packet id for a packet in memory.

newbasic/oncsEvent.cc, newbasic/oncsSubevent.cc, newbasic/oncsSubevent.h
fixed a potential race condition in the Event object
implemented the copy function proper for packet data.
There could be a race condition while traversing the event's data for the packets. We move from packet start to packet start. If in a corrupt event the packet length was 0, we would get into an infinite loop since there was no check. I added that check.
There is a also a rarely-used member function that allows one to copy the packet's data to external memory for various purposes. This was not implemented or all packet types. Done.
=> mlp - fixed a potential race condition in the Event object

newbasic/Event.h, newbasic/Eventiterator.h, newbasic/caen_correction.cc, newbasic/oncsSub_idcaenv1742.cc, newbasic/packet.h
I found that a function prototype like
`virtual void listFrame( const int id=0, std::ostream& os=std::cout) const {};`
is flagged when using -Wall -Werror -Wextra complier flags. I changed this in the top-level includes to like
`virtual void listFrame( const int /*id*/ =0, std::ostream& /*os*/=std::cout) const {};`
so we keep a hint what that parameter means and yet satisfy the compiler. There might be more such instances but so far it looks ok.
=> top-level header changes to satisfy -Werror -Wall -Wextra

newbasic/configure.ac
clang 14 produces one more additional warning, added it to the -Wno flags
=> one more warning suppression for clang

pmonitor/Makefile.am
replaced -I$(ROOTSYS) by -isystem$(ROOTSYS) so root headers don't cause warnings
=> fix clang 14 compilation

newbasic/Makefile.am
scan-build with llvm 14 crashes in jenkins with a missing ioselect.h. The Makefile has one explicit dependency for it to install the header. As of a while ago we also create the dictionaries during the install header step. If this gets called before headers are installed (jenkins does seem to behave differently here, I don't se this in the daily scan build), scan-build dies with a missing ioselect.h. This PR adds ioselect.h explicitly to the dictionary dependency, so it will be created before rootcint is called
=> add ioselect to Dict dependency to force timely creation

newbasic/Makefile.am
This one slipped through - the msg dictionary also needs ioselect.h
=> add dep on ioselect to msg dict

newbasic/.gitingore, newbasic/oncsSub_idtpcfeev3.cc, newbasic/oncsSub_idtpcfeev3.h
Extend `oncsSub_idtpcfeev3` to support timeframe tagger, which mark begin (level-1 trigger) and end (Endat) of a TPC timeframe which allows for: 
1. TPC timeframe building with respect to each level-1 trigger, even without GL1 PRDF
2. QA check TPC triggers against GL1 events
3. QA check TPC waveforms against trigger throttling window that is marked by the  begin and end taggers
4. Mark overlapping timeframes below to two or more close-by triggers
Tested with recent runs: 
```
ddump -n 30  /sphenix/lustre01/sphnxpro/rawdata/commissioning/tpc/pedestal/TPC_ebdc14_pedestal-00010628-0000.prdf  | grep Packet -A 5
Packet  4140 16388 -1 (sPHENIX Packet) 120 (IDTPCFEEV3)
TAGGER_TYPE    BCO          LEVEL1 CNT  ENDAT CNT     LAST_BCO     MODEBITS
0xbbf0 (LVL1 ) 470515440507       7092       7047 …
```
=> Extend `oncsSub_idtpcfeev3` to support timeframe tagger

newbasic/packet_idcstr.cc
We came across never-seen-before 0-length idcstr packets that caused a segfault. Fixed.
=> mlp - fixed a segfault if the packet happens to have no data

newbasic/A_Event.cc, newbasic/Makefile.am, newbasic/configure.ac, newbasic/oncsSub_idinttv0.cc, newbasic/oncsSub_idinttv0.h, newbasic/oncsSub_idtpcfeev3.cc, newbasic/oncsSub_idtpcfeev3.h, newbasic/packetConstants.h, newbasic/packet_collection.h, newbasic/packet_iddigitizerv3.cc, newbasic/packet_iddigitizerv3.h, newbasic/packet_mnemonic.cc
This packaging and wrapping up Dan's work on the new decoder for the 160++ hitformats. We assigned them so that the hitformat is 160 + nr_of_samples, so for 12 samples we get 172. 
This is better than for the old data format where the hitformats were assigned differently, and we only supported 12, 16, and 31 samples. This supports any valid sample number. Note that the sample nr needs to be even, so we can have 2,4,6,....,30.
=> added support for the "packed" / zero-suppressed calorimeter hitformats

newbasic/oncsSub_idtpcfeev3.cc, newbasic/oncsSub_idtpcfeev3.h
The current official version of the "cachedIterator" had a stupid bug that prevented it from actually caching the earlier result, so for every query it would make a full iterator search. That fix made about a factor of 60 difference. I then streamlined the decoding further and gained about a factor of 70 in speed overall. Here is the result of a 100-event ddump before and after:
```
$ time ddump  -n 100 /data/tpc/TPC_ebdc00_beam-00021560-0000.prdf > /dev/null
real    6m24.404s
user    6m23.380s
sys     0m1.004s
```
After the first fix:
```
$ time ddump  -n 100 /data/tpc/TPC_ebdc00_beam-00021560-0000.prdf > /dev/null
real    0m6.458s
user    0m5.573s
sys     0m0.884s
```
With the current version:
```
$ time ddump  -n 100 /data/tpc/TPC_ebdc00_beam-00021560-0000.prdf > /dev/null```
real …
=> speed-up of TPC decoding

newbasic/oncsSub_idcaenv1742.cc, newbasic/packet_iddigitizerv2.cc, newbasic/packet_iddigitizerv3.cc, newbasic/packet_iddigitizerv3.h
With the digitizer decoders so far we had interfaces "EVENCHECKSUMOK" and "ODDCHECKSUMOK" that would show the checksum status for the even and odd channels. Due to the hardware design, those are calculated independently. With the advent of the new zero-suppressed formats where those checksums don't exist, this interface returned 0, interpreted as "wrong checksum". 
For backward-compatibility, I added those interfaces that always return -1, meaning "cannot be determined". 
I have implemented a more generic interface "CHECKSUMOK" that works for all hitformats. Let's retire the old "odd" and "even" checks in favor of this one. 
Keep in mind that all checksum interfaces have a "tri-state" output:
1 - checksum is ok
0 - checksum is wrong
-1 - checksum cannot be evaluated.
Each time we have a …
=> fixes to the checksum interfaces for the new zero-suppressed digitizer formats

newbasic/eventServer.cc
clang complains about an uninitialized variable. It's a this will never happen case but clang doesn't know
=> initialize status to make clang happy

eventlibraries
We got derailed with changing the ugly name "newbasic" that predates git to "eventlibraries". This new name has already been documented in the manual for a while. In 2020 we had back out of the name change due to too many automated installation scripts breaking. This is easing us into the name change in a gentle way.
=> in the quest to eventually phase out the "newbasic" name, I added an "eventlibraries" symlink

newbasic/oncsSub_idmvtxv3.cc, newbasic/oncsSub_idmvtxv3.h
This PR introduce a method to get initial packet data pointer which is used to direct pooling data in the mvdx decoder.
=> ycm - add pValue function which return pointer to packet data

newbasic/lastEvent.cc, newbasic/oncsSubevent.cc
So far, the only way to find the last event in a file was to traverse the entire file (because files are in all other contexts treated as non-direct-access streams). This utility adds an efficient way to get at the last event(s) in a file, which in sPHENIX is needed in several contexts. It goes to the end of the file and works its way backwards to the beginning of a new buffer. It so gets fast access to the last few events in that buffer. In a single-file run, this is usually the end-run event:
```
lastEvent   /mac_home/data/V1742/rcdaq-00000003-0000.evt
-- Event    20 Run:     3 length:     8 type: 12 (End Run Event)  1515015411
```
but with file rollover this is not normally the case.
Options (lastEvent -h):
```
lastEvent finds the last event(s) in a given file in an efficient way.
List …
```
=> added a new "lastEvent" utility that can efficiently find the last event in a raw data file

newbasic/eventServer.cc
I forgot I need to convert() the event if it's not from an online stream. Fixed.
=> mlp - small fix in the eventServer 

newbasic/oncsSub_idtpcfeev3.cc, newbasic/oncsSub_idtpcfeev3.h
The decoder was modified so that it works both for non-ZS and ZS mode. 
Until the N'th sample missing issue is fixed and additional sync word is added, the data format will be kept as it is.
=> Modified decoder that works consistently with non-ZS and ZS mode

newbasic/packet_iddigitizerv3.cc
more out of a sense of completeness, I added the "EVTNR" as an lValue as well.
however, since the event number is really unlikely to run past 4 billion, here I left the iValue intact. So you get the same value.
=> mlp - I added the "EVTNR" as an lValue

newbasic/oncsSub_idtpcfeev3.cc
Implemented deleting sampa waveform class in case the data didn't pass the length consistency check.
=> fixed memory leak

newbasic/Makefile.am, newbasic/oncsCollection.h, newbasic/oncsEvent.cc, newbasic/oncsSubConstants.h, newbasic/oncsSub_idgl1v1.cc, newbasic/oncsSub_idgl1v1.h
Added a new hitformat (143 = IDGL1V1).
We reduced the number of GL1-P scalers to 12 (from 16), and added the "scaled" triggervector field.
In order to make it more consistent, I added an API
lValue(0, "LiveVector")
lValue(0, "ScaledVector")
"LiveVector" is the same as "TriggerVector", and that will continue to work and give the same as  "LiveVector".
=> added a new hitformat for the GL1 v1

newbasic/packet_idll1v2.cc
This PR restores the capability to dump the ll1 packets into a file (replace std::cout by ostream &os)
=> replace std::cout by ostream to dump to file

newbasic/oncsSub_idtpcfeev4.cc, newbasic/oncsSub_idtpcfeev4.h
This is aimed to fix memory errors identified in the Continuous Integration checks: 
https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-valgrind-StreamingProduction/386/valgrindResult/pid=323555/ 
1. Some FEE data buffer could go out of bound SAMPA data packet at the edge of the RCDAQ events: https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-valgrind-StreamingProduction/386/valgrindResult/pid=323555,0x1a3d/ 
2. Unconditional jump on uninitialized variables due to they are not always filled in decoder: https://web.sdcc.bnl.gov/jenkins-sphenix/job/sPHENIX/job/test-default-valgrind-StreamingProduction/386/valgrindResult/pid=323555,0x9e7/
=> Memory error fixes on `oncsSub_idtpcfeev4`

newbasic/mvtx_decoder/mvtx_utils.h
The OnlMon problem "no events filled in histograms" is fixed by this PR. Change 16 bits ``flxHdrSize`` to 8 bits, so that we can get correct RDH.
=> fix mvtx checkRDH problem

newbasic/oncsSub_idinttv0.cc, newbasic/oncsSub_idinttv0.h
ddump now lists
>Packet  3001   324 -1 (sPHENIX Packet) 110 (IDINTTV0)
> Number of unique BCOs: 2
> BCO   0:  0x19f842a0b7    number of FEEs for this BCO  14
>           Number of unique FEEs:    0   1   2   3   4   5   6   7   8  9  10  11  12  13
> BCO   1:  0x19f842a357    number of FEEs for this BCO   7
>           Number of unique FEEs:    0   3   4   5   7   8  13
> Number of hits: 190
>      FEE    BCO      chip_BCO  chip_id channel_id    ADC  full_phx
>      full_ROC Ampl.
>   0     0  19f842a0b7   0x1f       2        80         0     0 0       0     0x0150001f
>   1     0  19f842a0b7   0x1f       2        86         0     0 0       0     0x0156001f
>...
=> mlp - added the desired APIs to get the FEEs per BCO out of a packet.

newbasic/Makefile.am, newbasic/eventServer_classic.cc
resurrected the older eventServer version and features as eventServer_classic.
$ eventServer_classic -h
gl1_server serves events from a given datastream
List of options:
-d <number> depth of buffer
-f (stream is a file)
-T (stream is a test stream)
-r (stream is a rcdaq monitoring stream)
-O (stream is a legacy ONCS format file)
-L (stream is a file list)
-x act as a one-event-at-a-time server (depth is irrelevant)
-h this message
debug options
-s <number> sleep so many ticks (in units of usleep)
-i <print event identity>
-v verbose
-c count  print -v -or -i messages only every <count> occurences
=> mlp - resurrected the older eventServer version as eventServer_classic

newbasic/Makefile.am
This PR adds -lbz2 to libEvent, libNoRootEvent lib dependencies, removes dep on libbz2,liblzo2 from executables (now satisfied by libEvent, libNoRootEven)
=> move lib dependencies on compression libs to libEvent, libNoRootEvent

newbasic/oncsSub_idtpcfeev4.cc
Handling the waveform vector more efficient this speeds up the tpc reading by close to a factor of 2
=> replace push_back by resize(), fill()

newbasic/oncsSub_idtpcfeev4.cc, newbasic/oncsSub_idtpcfeev4.h
Another x6 speedup for the bco search by decoding the gtm data separately and only do the waveform decoding if waveforms are requested
=> Tpcspeedup 2

newbasic/oncsSub_idmvtxv3.cc
At Jakubs suggestion, a clear was added to any MVTX lanes that see a decoding error. This is hard to test that it solves our memory issue without first deploying it to find a decoding error
=> CD: Added a clear to MVTX lanes w/ decoding errors

newbasic/oncsSub_idtpcfeev4.cc, newbasic/oncsSub_idtpcfeev4.h
This is a IPA function to get # of valid FEEs w/o accessing waveform info in a faster way. 
@pinkenburg let me know if this doesn't make sense with your merge from yesterday
=> IPA function to get # of valid FEEs w/o accessing waveform info

newbasic/oncsSub_idcaenv1742.cc
fixed a bug in the CAEN1742 decoder that derailed the decoding if not all readout groups were enabled.
I also added both the TR0 and TR1 values to ddump instead of just TR0 - as we are moving to more elaborate triggering schemes in the line laser orbit, TR0 and TR1 are not longer usually the same.
=> mlp - fixed a bug in the CAEN1742 decoder

newbasic/Makefile.am
This PR adds subdir-objects to the automake options to get rid of the subdir warning under Alma9. This option seems compatible with our SL7 automake, so it shouldn't change anything
=> add subdir-objects to AUTOMAKE_OPTIONS

.gitignore, newbasic/.gitignore, newbasic/.gitingore, newbasic/oncsSub_idmvtxv3.cc, newbasic/oncsSub_idmvtxv3.h
Added a new generic dump function for MVTX that overrides the char based gdump and adds GBT description to the hex format generic gdump, while also formatting the printout into FELIX packets as described in the MVTX data format
=> Add MVTX specific gdump

newbasic/packet_iddigitizerv2.cc, newbasic/packet_iddigitizerv2.h
Using lValue to get the clock for these packets results in having a negative 64 bit long long once the clock counter exceeds 0x8000000 which then throws off any clock difference calculations. resulting in 0xFFFFFFFF8000000 instead of 0x8000000. The reason is that currently the iValue is returned which is an int which then turns the long long into a negative value
=> implement lValue for packet_iddigitizerv2 clock,eventnr

newbasic/packet_iddigitizerv3.cc
an ad-hoc fix to a race condition in the packet_iddigitizerv3.cc decoder. In a certain fraction of events we get into an infinite loop here. For now I abort the decoding, but this deserves a closer look.
=> mlp - an ad-hoc fix to a race condition in the packet_iddigitizerv3.cc

newbasic/eventServer_classic.cc
Example usage:
eventServer_classic -e 1,200000 -f <gl1.evt>
Then read in segment 0 of your subsystem prdf. The first 200K events will be available.
=> added -e option to eventServer_classic so that it buffers specific event range

newbasic/configure.ac
small addition to the configure.ac to compile it with the new clang version (20.1.8)
=> needs -Wno-nontrivial-memcall for clang 20
